ecommerceapp/cart/urls.py
from django.contrib import admin
from django.urls import path,include
from cart import views
app_name="cart"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('add_address/', views.add_address, name='add_address'),
    path('update_address/', views.update_address, name='update_address'),
    path('delete_address/', views.delete_address, name='delete_address'),
    path('cart/',views.cartview,name="cartview"),
    path('addcart/<n>',views.addtocart,name="addtocart"),
    path('remove_quantity/<n>',views.remove_quantity,name="removequantity"),
    path('delete_item/<n>',views.delete_item,name="delete"),
    path('orderform/',views.order_form,name="orderform"),
    path('order_confirm/',views.order_confirm,name="orderconfirm"),
    path('view_orders/',views.orders,name="orders"),
   
    
    

    


    
]

ecommerceapp/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from ecommerce import views
app_name="ecommerce"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name="home"),
    path('category/<n>',views.category,name="category"),
    path('Products/',views.products,name="products",),
    path('singleproduct/<int:pk>',views.singleproduct,name="singleprdt"),
    path('register/',views.register,name="register"),
    path('login/',views.user_login,name="login"),
    path('logout/',views.user_logout,name="logout"),
    path('favourite/<int:pk>',views.favourite,name="favo"),
    path('fav_view',views.favor_view,name="fav_view"),
    path('user_profile',views.update_profile,name="userprofile"),
]

ecommerceapp/ecommerceapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from cart import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecommerce.urls')),
    path('cart_view/',include('cart.urls')),
    path('search/',include('search.urls')),
    path('proceed-to-pay/',views.razorpaycheck,name="proceed-to-pay")
    


    

]


if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerceapp/search/urls.py
from django.contrib import admin
from django.urls import path,include
from search import views

app_name="search"

urlpatterns = [
    path('search_result/', views.search,name='search'),
    
]

ecommerceapp/cart/models.py
from django.db import models
from django.db import models
from ecommerce.models import Product
from django.contrib.auth.models import User
import django.utils.timezone

# Create your models here.


class Cart(models.Model):

    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity = models.IntegerField()
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def subtotal(self):
        return self.quantity*self.product.price

ORDER_STATUS_CHOICES = [
    ('placed', 'Order Placed'),
    ('shipped', 'Shipped'),
    ('delivered', 'Delivered'),
    ('cancelled', 'Cancelled'),
]

DELIVERY_STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('shipped', 'Shipped'),
    ('out_for_delivery', 'Out for Delivery'),
    ('delivered', 'Delivered'),
]

PAYMENT_STATUS_CHOICES=[('cod','cash on delivery'),
                        ('op','online payment')]

class Address(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    phone=models.IntegerField()
    address=models.TextField()
    zip_code = models.CharField(max_length=12)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    
    
    def __str__(self):
        return self.user.username


class Order(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    address=models.ForeignKey(Address,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    no_of_items=models.IntegerField(default='#')
    order_status = models.CharField(max_length=20, choices=ORDER_STATUS_CHOICES, default='placed')
    payment_status = models.CharField(max_length=20, choices=PAYMENT_STATUS_CHOICES, default='pending')
    delivery_status = models.CharField(max_length=20, choices=DELIVERY_STATUS_CHOICES, default='pending')
    ordered_date=models.DateTimeField(auto_now_add=True)
    payment_id=models.CharField(max_length=100,default='#')

    def __str__(self):
        return self.user.username


# Create your models here.

ecommerceapp/search/models.py
from django.db import models

# Create your models here.

ecommerceapp/cart/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Cart,Address,Order
from ecommerce.models import Category,Product
from django.contrib.auth.decorators import login_required
from decimal import Decimal            
from django.conf import settings
import razorpay
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseBadRequest
import secrets
import string
from django.http import JsonResponse
import json
from django.contrib import messages
from ecommerce.forms import UserForm,AddressForm
# Create your views here.


@login_required
def add_address(request):
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            messages.success(request, 'Address added successfully!')
            return redirect('ecommerce:userprofile')  
    else:
        form = AddressForm()
    return render(request, 'add_address.html', {'form': form})

@login_required
def update_address(request):
    user_address = Address.objects.get(user=request.user)
    if request.method == 'POST':
        form = AddressForm(request.POST,instance=user_address)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your profile has been updated successfully!')
            return redirect('ecommerce:userprofile')
    else:
        form=AddressForm(instance=user_address)
    return render(request, 'update_address.html', {'form': form,})


@login_required
def delete_address(request):
    user_address = Address.objects.get(user=request.user)
    if user_address:
        user_address.delete()
        return redirect('ecommerce:userprofile')

@login_required
def cartview(request):
    try:
        user_address = Address.objects.get(user=request.user)
    except Address.DoesNotExist:
        user_address = None
        messages.error(request, "You need to add an address before placing an order.")
        
    
    u=request.user
    cart=Cart.objects.filter(user=u)
    
    total=0
    for i in cart:
        total+=i.quantity*i.product.price

     
    offer=Decimal('0')
    discount = Decimal('0')
    
    if total >= Decimal('1000'):
        discount = Decimal('0.2') * total  # 20% discount
        offer=total-discount

    return render(request,'cartview.html',{'c':cart,'t':total,'d':discount,'dis':offer,'address':user_address})




@login_required
def addtocart(request,n):

    p=Product.objects.get(name=n)
    u=request.user#current login user
    try:
        cart=Cart.objects.get(user=u,product=p) #it checks if product is already added to cart else except will work
        if(p.stock > 0):
            cart.quantity+=1  # it add one quantity to that particular product
            cart.save()
            p.stock-=1  #after adding quantity and the quantity of that particular product is taken from the stock field so we also need to decrease the stock of that product
            p.save()
    except:
        if(p.stock > 0):
            cart=Cart.objects.create(product=p,user=u,quantity=1) #when we adding first time a product to cart so this will create a cart of that particular product with one quantity
            cart.save()
            p.stock-=1
            p.save()
    return cartview(request)

@login_required
def remove_quantity(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        if(cart.quantity>1):
            cart.quantity-=1
            cart.save()
            p.stock+=1
            p.save()

        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
        pass

    return cartview(request)


@login_required
def delete_item(request,n):
    p=Product.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,product=p)
        cart.delete()
        p.stock+=cart.quantity
        p.save()
    except:
        pass

    return cartview(request)



################### razorpay payment with jquery in below################


@login_required
def order_form(request):

    try:
        user_address = Address.objects.get(user=request.user)
    except Address.DoesNotExist:
        messages.error(request, "You need to add an address before placing an order.")
        return redirect('cart:add_address')
    
    if request.method == "POST":
        payment_method = 'cod'
        cart=Cart.objects.filter(user=request.user)

        total = Decimal('0')
        for i in cart:
            total+=i.quantity*i.product.price

        if total >= Decimal('1000'):
            discount = Decimal('0.2') * total  # 20% discount
            amount=total-discount
        else:
            amount=total
        
        for i in cart:
            address_obj = Order.objects.create(
            user=request.user,
            product=i.product,
            address=user_address,
            payment_status=payment_method,
            no_of_items=i.quantity,
            payment_id='cod'
                )
            
            address_obj.save()

            cart.delete()

    return redirect('cart:orderconfirm')


@login_required
def order_confirm(request):
    return render(request,'order_confirm.html')



@login_required
def razorpaycheck(request):
    cart=Cart.objects.filter(user=request.user)
    user=request.user
    email=user.email
    name = user.get_full_name()
    total = Decimal('0')
    for i in cart:
        total+=i.quantity*i.product.price
    if total >= Decimal('1000'):
        discount = Decimal('0.2') * total  # 20% discount
        amount=total-discount
    else:
        amount=total

    return JsonResponse({
        'total_price':amount,
        'user_name': name,
        'user_email': email,

    })


@login_required
def orders(request):
    user=request.user
    orders=Order.objects.filter(user=user)
    
    return render(request,'orderpage.html',{'orders':orders})

ecommerceapp/search/views.py
from django.shortcuts import render
from django.db.models import Q
from ecommerce.models import Product,Category

def search(request):
    query = ""
    products = None
    if (request.method == "POST"):
        query = request.POST['q']
        if (query):
            products = Product.objects.filter(Q(name__icontains=query) | Q(price__icontains = query) | Q(category__name__icontains=query))
        
    return render(request, 'search.html', {'query': query, 'b': products})

ecommerceapp/templates/cartview.html
{%extends 'base.html'%}
{%load static%}

{%block content%}

<div class="card">
    <div class="row ">
        <div class="col-md-8 cart">
            <div class="title ">
                <div class="row">
                    <div class="col"><h4><b>Shopping Cart</b></h4></div>
                    <div class="col align-self-center text-right text-muted">{{count}}</div>
                </div>
            </div>
            {% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} text-danger"><b>{{ message }}</b></div>
    {% endfor %}
    {% endif %}
            {%for i in c %}    
            <div class="row border-top border-bottom">
                <div class="row main align-items-center">
                    <div class="col-2"><img class="img-fluid" src="{{i.product.image.url}}"></div>
                    <div class="col">
                        <div class="row text-muted">{{i.product.name}}</div>
                        <div class="row">category : {{i.product.category}}</div>
                    </div>
                    <div class="col">
                        <a href="{% url 'cart:removequantity' i.product.name %}">-</a><a href="#" class="border">{{i.quantity}}</a><a href="{% url 'cart:addtocart' i.product.name %}">+</a>
                    </div>
                    <div class="col">{{i.product.price}} <a href="{% url 'cart:delete' i.product.name %}"><span class="close">&#10005;</span></a></div>
                </div>
            </div>
            {%endfor%}
            <div class="back-to-shop"><a href="{%url 'ecommerce:products' %}">&leftarrow;</a><span class="text-muted">Back to shop</span></div>
        </div>
        <div class="col-md-4 summary pt-5">
            <div><h5><b>Summary</b></h5></div>
            <hr>
            <div class="row">
                <div class="col" style="padding-left:0;">Discount 20% for Purchase above 1000</div>
                
            </div>
        
            {%if t >= 1000 %}
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                <div class="col">TOTAL</div>
                <div class="col text-right"><b>{{ t }}</b></div>
            </div>
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                <div class="col"><i><span class="text-dark">Discount &nbsp;20%</i></span></div>
                <div class="col text-right">-<i>{{ d }}</i></div>
            </div>
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                <div class="col">Grand Total</div>
                <div class="col text-right"><b>{{ dis }}/-</b></div>
            </div>
            {%else%}
            <div class="row" style="border-top: 1px solid rgba(0,0,0,.1); padding: 2vh 0;">
                <div class="col">TOTAL</div>
                <div class="col text-right"><b>{{ t }}/-</b></div>
            </div>
            {%endif%}
            {%if t > 1 %}
            <a href="" data-bs-toggle="modal" data-bs-target="#bookingModal" class="btn">Checkout</a>
            {%endif%}
        </div>
    </div>
</div>
<div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bookingModalLabel">Checkout form</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

    <form id="bookingForm" method="POST" action="{% url 'cart:orderform' %}">
        {% csrf_token %}
        <div class="mb-3">
        <p><b>Total: </b>{{ t }}/-</p>
        <p><b>Discount:</b> {{ d }}</p>
        <p><b>Total after discount:</b> {{ dis }}</p>
        <p><b>Address:</b> {{ address.address }}</p>
        <p><b>City:</b> {{ address.city }}</p>
        <p><b>Country: </b>{{ address.country }}</p>
        <p><b>Zip Code:</b> {{ address.zip_code }}</p>
        <p><b>Phone: </b>{{ address.phone }}</p>
        {%if address%}
    <a href="{% url 'cart:update_address' %}" class="text-primary text-decoration-underline">edit Address</a>
    {%else%}
    <a href="{% url 'cart:add_address' %}" class="text-primary text-decoration-underline">Click here to Add Address</a>
    {%endif%}
        </div>
        <div id="formMessage" class="alert d-none"></div>
        <button type="submit" class="btn btn-success">Cash on delivery</button>
        <button type="button" class="btn btn-info paywithrazorpay">Razorpay</button>
    </form>
</div>

        </div>
    </div>
</div>
<script>
    document.getElementById('bookingForm').addEventListener('submit', function(event) {
        // Show success message
        var formMessage = document.getElementById('formMessage');
        formMessage.innerHTML = 'order placed successfully!';
        formMessage.classList.remove('alert-danger'); // Remove any error classes
        formMessage.classList.add('alert-success'); // Add success class
        formMessage.classList.remove('d-none'); // Show the message

        // Allow the form to submit after showing the success message
        setTimeout(function() {
            formMessage.classList.add('d-none'); // Hide the message again
            event.target.submit(); // Manually submit the form
        }, 10000); // Adjust the delay (in milliseconds) as needed
    });
</script>
  {%endblock%}


  {%block scripts%}
    <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> 
{%endblock scripts%}

ecommerceapp/templates/cat_based_products.html
{% extends 'base.html'%}
{% load static%}
{%block content%}


    <!-- ***** Products Area Starts ***** -->
    <section class="section mt-3 pt-5" id="products">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                    <div class="section-heading">
                        <h2>Products from {{cat.name}}'s Category</h2>
                        <span>Check out all of our products.</span>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="container">
            <div class="row">
                {%for i in prdt%}
                <div class="col-lg-4">
                    <div class="item">
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{%url 'ecommerce:singleprdt' i.pk%}"><i class="fa fa-eye"></i></a></li>
                                    
                                    <li><a href="{%url 'cart:addtocart' i.name%}"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <img src="{{i.image.url}}" alt="">
                        </div>
                        <div class="down-content">
                            <h4>{{i.name}}</h4>
                            <span>{{i.price}}</span>
                            <ul class="stars">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                        </div>
                    </div>
                </div>
               {%endfor%}
            </div>
        </div>
    </section>

{% endblock %}
    

ecommerceapp/templates/favo.html
{%extends 'base.html'%}
{%load static%}
{%block content%}

    <!-- ***** Products Area Starts ***** -->
    <section class="section" id="products">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 mt-5">
                    <div class="section-heading">
                        <h2>Favourites</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                {%for i in f%}
                <div class="col-lg-4">
                    
                    <div class="item">
                        
                        <div class="thumb">
                            <div class="hover-content">
                                <ul>
                                    <li><a href="{%url 'ecommerce:singleprdt' i.item.pk%}"><i class="fa fa-eye"></i></a></li>
                                    
                                    <li><a href="single-product.html"><i class="fa fa-shopping-cart"></i></a></li>
                                </ul>
                            </div>
                            <img src="{{i.item.image.url}}" alt="">
                        </div>
                        <div class="down-content">
                            <h4>{{i.item.name}}</h4>
                            <span>${{i.item.price}}</span>
                            <ul class="stars">
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                                <li><i class="fa fa-star"></i></li>
                            </ul>
                        </div>
                    </div>
                   
                </div>
                {%endfor%}
                
    </section>
    <!-- ***** Products Area Ends ***** -->
    {%endblock%}

ecommerceapp/templates/nav.html
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="navbar navbar-expand-lg main-nav">
                    <!-- ***** Logo Start ***** -->
                    <a href="index.html" class="navbar-brand logo">
                        <img src="{% static 'images/logo.png' %}">
                    </a>
                    <!-- ***** Logo End ***** -->
                    <!-- ***** Toggler/Collapsible Button Start ***** -->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"><i class="fa-solid fa-bars"></i></span>
                    </button>
                    <!-- ***** Toggler/Collapsible Button End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ms-auto bg-light">
                            <li class="nav-item scroll-to-section"><a href="{% url 'ecommerce:home' %}" class="nav-link active">Home</a></li>
                            <li class="nav-item scroll-to-section"><a href="{% url 'ecommerce:products' %}" class="nav-link">All Products</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="categoriesDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Categories</a>
                                <div class="dropdown-menu" aria-labelledby="categoriesDropdown">
                                    {% for i in links %}
                                    <a class="dropdown-item" href="{% url 'ecommerce:category' i.name %}">{{ i.name }}</a>
                                    {% endfor %}
                                </div>
                            </li>
                            {% if user.is_authenticated %}
                            <li class="nav-item"><a class="nav-link" href="{% url 'cart:cartview' %}"><sup class="text-warning">{{ count }}</sup><i class="fa fa-shopping-cart" style="font-size:25px;"></i></a></li>
                            <li class="nav-item"><a class="nav-link ms-1" href="{% url 'ecommerce:fav_view' %}"><i class="fa-solid fa-heart" style="font-size:25px;"></i></a></li>
                            <li class="nav-item scroll-to-section"><a class="nav-link" href="{% url 'ecommerce:logout' %}">Logout</a></li>
                            {% else %}
                            <li class="nav-item scroll-to-section"><a href="{% url 'ecommerce:register' %}" class="nav-link">Register</a></li>
                            {% endif %}
                        </ul>
                        <form class="d-flex ms-3 " method="POST" action="">
                            {% csrf_token %}
                            <input class="form-control me-3 mt-3 " type="search" placeholder="Search" name="q" >
                            <div class="">
                            <button class="btn btn-outline-success fs-6 rounded me-3  " type="submit">Search</button>
                        </div>
                        </form>
                    </div>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>

ecommerceapp/templates/order_confirm.html
{%extends 'base.html' %}
{%load static%}

{%block content%}


<div style="padding-top: 130px;padding-bottom: 120px;">
<h3 class="text-center mt-5">Order Confirmed</h4>
<h6 class="text-center">Click here to <a href="{%url 'ecommerce:products'%}" class="text-info">continue shopping</a></h4>
</div>


{%endblock%}

ecommerceapp/templates/userprofile.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
{% block extra_css %}
<link rel="stylesheet"  href="{% static 'css/userprofile.css' %}">
{% endblock %}
<section class="bg-light">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 mb-4 mb-sm-5">
                <div class="card card-style1 border-0">
                    <div class="card-body p-1-9 p-sm-2-3 p-md-6 p-lg-7">
                        <div class="row align-items-center">
                            {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} text-dark"><b>{{ message }}</b></div>
                            {% endfor %}
                            {% endif %}
                            <div class="col-lg-6 mb-4 mb-lg-0 pt-3 ps-5">
                                {% if user_profile.profile %}
                                    <img src="{{ user_profile.profile.url }}" alt="{{ user.username }}" class="rounded-3 " id="currentProfileImage"><br>
                                {% else %}
                                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" class="rounded-3 " alt="..." id="currentProfileImage"><br>
                                {% endif %}
                                <a href="" data-bs-toggle="modal" data-bs-target="#bookingModal" class="btnn"><i class="fa-solid fa-pen-to-square fs-5"></i></a>
                            </div>
                            <div class="col-md-6 px-xl-10">
                                <div class="bg-dark d-lg-inline-block py-1-9 px-1-9 px-sm-6 mb-1-9 rounded">
                                    <h3 class="h1 text-white mb-0 text-center ps-5 pe-5">{{ user.username }}</h3>
                                    <a href="{% url 'cart:orders' %}"><button class="btn btn-danger text-white">My orders</button></a>
                                </div>
                                <ul class="list-unstyled mb-1-9">
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Full Name:</span> {{ user.first_name }} {{ user.last_name }} </li>
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Mail address:</span> {{ user.email }}</li>
                                    {%if address%}
                                    <li class="mb-2 mb-xl-3 display-28"><span class="display-26 text-secondary me-2 font-weight-600">Address:</span> {{ address.address }}<br>
                                    {{address.city}},
                                    {{address.country}}<br>
                                    {{address.zip_code}}</li>
                                    <li class="display-28"><span class="display-26 text-secondary me-2 font-weight-600">Phone:</span>{{address.phone}}</li>
                                    {%endif%}
                                </ul>
                                <div class="button-container "> 
                                    {%if address%}
                                    
                                    <a href="{% url 'cart:update_address' %}"class="button1 btn btn-secondary text-white">Edit Address</a>
                                    <a href="{% url 'cart:delete_address' %}" class="button1 btn btn-secondary "><i class="fa-solid fa-trash"></i></a>
                                    {%else%}
                                    <a href="{% url 'cart:add_address' %}" class="button1 btn btn-secondary text-white ">Add Address</a>
                                    {%endif%}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="bookingModal" tabindex="-1" aria-labelledby="bookingModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="bookingModalLabel">Profile Update</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form method="POST" id="bookingForm" enctype="multipart/form-data" class="needs-validation" novalidate>
                        {% csrf_token %}
                        
                        <!-- Custom file input with onchange event -->
                        <div class="form-group mb-3">
                            <label for="profile" class="form-label">Profile Image</label>
                            <input class="form-control" type="file" name="profile" id="profile" onchange="previewImage(event)">
                            <div class="form-check mt-2">
                                <input class="form-check-input" type="checkbox" name="profile-clear" id="profile-clear">
                                <label class="form-check-label" for="profile-clear">Clear</label>
                            </div>
                        </div>
                        
                        <!-- Image preview element -->
                        <div class="form-group mb-3">
                            <img id="imagePreview" src="#" alt="Selected Image" class="rounded-3" width="150" height="150" style="display: none;">
                        </div>
                        
                        <button type="submit" class="btn btn-primary">Save changes</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

<script>
function previewImage(event) {
    var reader = new FileReader();
    reader.onload = function() {
        var output = document.getElementById('imagePreview');
        output.src = reader.result;
        output.style.display = 'block'; // Show the image preview
    }
    reader.readAsDataURL(event.target.files[0]);
}

// Handle clear checkbox
document.getElementById('profile-clear').addEventListener('change', function() {
    if (this.checked) {
        var output = document.getElementById('imagePreview');
        output.src = '';
        output.style.display = 'none'; // Hide the image preview
        document.getElementById('profile').value = ''; // Clear the file input
    }
});
</script>
{% endblock %}